env:
  global:
    secure: $VSCE_AUTH_TOKEN
language: node_js
node_js:
  - node
install:
  - npm install
  - npm install -g vsce
script:
  - npm run build
  - vsce package
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      tags: true
