env:
  global:
    secure: $VSCE_AUTH_TOKEN
after_success:
  - npm install -g vsce;
  - vsce package;
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: markypython/OneDark-Pro
      tags: true
  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: markypython/OneDark-Pro
      tags: true
