%YAML 1.2
---
colors:
  purple: '#c678dd'
  error: '#f44747'
  coral: '#e06c75'
  whiskey: '#d19a66'
  chalky: '#e5c07b'
  lightDark: '#5c6370'
  dark: '#5c6370'
  malibu: '#61afef'
  green: '#98c379'
  fountainBlue: '#56b6c2'
  invalid: '#ffffff'
  lightWhite: '#bbbbbb'
foreground:
  purple:
    - support.constant.edge
    - keyword.operator.expression.instanceof
    - keyword.operator.new
    - keyword.operator.ternary
    - keyword.operator.optional
    - keyword.operator.assignment.c
    - keyword.operator.comparison.c
    - keyword.operator.c
    - keyword.operator.increment.c
    - keyword.operator.decrement.c
    - keyword.operator.bitwise.shift.c
    - punctuation.separator.c
    - keyword.operator.sizeof.c
    - keyword.operator.logical.python
    - keyword.operator.assignment.compound
    - keyword
    - token.package.keyword
    - keyword.control
    - storage
    - token.storage
    - keyword.operator.expression.delete
    - keyword.operator.expression.in
    - keyword.operator.expression.of
    - keyword.operator.expression.instanceof
    - keyword.operator.new
    - keyword.operator.expression.typeof
    - keyword.operator.expression.void
    - meta.selector
    - markup.italic
    - punctuation.definition.italic
    - todo.emphasis
    - emphasismd
    - markup.underline.link.markdown
    - markup.underline.link.image.markdown
    - text.html.laravel-bladesource.php.embedded.line.htmlentity.name.tag.laravel-blade
    - text.html.laravel-bladesource.php.embedded.line.htmlsupport.constant.laravel-blade
    - keyword.operator.error-control.php
    - keyword.operator.type.php
    - keyword.operator.regexp.php
    - keyword.operator.heredoc.php
    - keyword.operator.nowdoc.php
    - token.debug-token
    - punctuation.definition.template-expression.begin
    - punctuation.definition.template-expression.end
    - punctuation.section.embedded
    - keyword.operator.module
    - punctuation.quasi.element
    - support.type.texture.hlsl
    - support.type.sampler.hlsl
    - support.type.object.hlsl
    - support.type.object.rw.hlsl
    - support.type.fx.hlsl
    - support.type.object.hlsl
    - variable.language.super
  coral:
    - constant.other.character-class.regexp
    - markup.deleted.diff
    - meta.function.c
    - source.java
    - meta.definition.variable.name.java
    - punctuation.definition.template-expression.begin
    - punctuation.definition.template-expression.end
    - support.type.object.console
    - support.variable.dom
    - support.variable.property.dom
    - meta.function-call.arguments.python
    - meta.function-call.python
    - variable.other.class.php
    - entity.name.tag
    - markup.heading
    - keyword.other.unit
    - entity.name.section.markdown
    - punctuation.definition.heading.markdown
    - punctuation.definition.list.begin.markdown
    - punctuation.definition.list.markdown
    - punctuation.definition.string.begin.markdown
    - punctuation.definition.string.end.markdown
    - punctuation.definition.metadata.markdown
    - beginning.punctuation.definition.list.markdown
    - punctuation.definition.metadata.markdown
    - punctuation.section.embedded
    - variable.interpolation
    - source.jsonmeta.structure.dictionary.json>string.quoted.json
    - source.jsonmeta.structure.dictionary.json>string.quoted.json>punctuation.string
    - support.type.property-name.json
    - support.type.property-name.jsonpunctuation
    - punctuation.definition.variable.php
    - selector.sass
    - entity.name.variable.local.cs
    - meta.property.object
    - variable.parameter.function.js
    - constant.character.entity
    - meta.symbol.clojure
    - meta.arguments.coffee
    - variable.parameter.function.coffee
    - meta.scope.prerequisites.makefile
    - meta.definition.variable.name.groovy
    - text.variable
    - text.bracketed
  whiskey:
    - keyword.operator.quantifier.regexp
    - support.constant.property.math
    - support.constant.property-value.scss
    - support.constant.property-value.css
    - support.constant.color.w3c-standard-color-name.css
    - support.constant.color.w3c-standard-color-name.scss
    - support.constant.color.w3c-standard-color-name.css
    - support.constant.json
    - support.variable.property.process
    - variable.parameter.function.language.python
    - variable.parameter.function.python
    - control.elements
    - keyword.operator.less
    - support.constant.font-name
    - constant.numeric
    - none
    - none
    - constant
    - punctuation.definition.constant
    - entity.other.attribute-name
    - entity.other.attribute-name.class.css
    - none
    - markup.bold
    - todo.bold
    - punctuation.definition.bold.markdown
    - support.constant.ext.php
    - support.constant.std.php
    - support.constant.core.php
    - support.constant.parser-token.php
    - function.parameter
    - inline-color-decorationrgb-value
    - lessrgb-value
    - token.warn-token
    - support.constant.elm
    - variable.other.constant
    - variable.parameter.function
    - variable.parameter
  green:
    - punctuation.definition.string.begin
    - punctuation.definition.string.end
    - markup.inserted.diff
    - constant.character.format.placeholder.other.python
    - string
    - entity.other.inherited-class
    - markup.inline.raw.markdown
    - markup.inline.raw.string.markdown
    - source.jsonmeta.structure.dictionary.json>value.json>string.quoted.json
    - source.jsonmeta.structure.array.json>value.json>string.quoted.json
    - source.jsonmeta.structure.dictionary.json>value.json>string.quoted.json>punctuation
    - source.jsonmeta.structure.array.json>value.json>string.quoted.json>punctuation
    - keyword.other.template.begin
    - keyword.other.template.end
    - keyword.other.substitution.begin
    - keyword.other.substitution.end
    - source.ini
    - meta.definition.class.inherited.classes.groovy
  lightWhite:
    - punctuation.section.block.begin.bracket.curly.cpp
    - punctuation.section.block.end.bracket.curly.cpp
    - punctuation.terminator.statement.c
    - punctuation.section.block.begin.bracket.curly.c
    - punctuation.section.block.end.bracket.curly.c
    - punctuation.section.parens.begin.bracket.round.c
    - punctuation.section.parens.end.bracket.round.c
    - punctuation.section.parameters.begin.bracket.round.c
    - punctuation.section.parameters.end.bracket.round.c
    - punctuation.separator.key-value
    - punctuation.section.block.begin.java
    - punctuation.section.block.end.java
    - punctuation.definition.method-parameters.begin.java
    - punctuation.definition.method-parameters.end.java
    - meta.method.identifier.java
    - punctuation.section.method.begin.java
    - punctuation.section.method.end.java
    - punctuation.terminator.java
    - punctuation.section.class.begin.java
    - punctuation.section.class.end.java
    - punctuation.section.inner-class.begin.java
    - punctuation.section.inner-class.end.java
    - meta.method-call.java
    - storage.type.generic.java
    - punctuation.section.class.begin.bracket.curly.java
    - punctuation.section.class.end.bracket.curly.java
    - punctuation.section.method.begin.bracket.curly.java
    - punctuation.section.method.end.bracket.curly.java
    - punctuation.separator.period.java
    - meta.method.body.java
    - punctuation.separator.list.comma.css
    - punctuation.separator.delimiter
    - punctuation.definition.arguments.begin.python
    - punctuation.definition.arguments.end.python
    - punctuation.separator.arguments.python
    - punctuation.definition.list.begin.python
    - punctuation.definition.list.end.python
    - meta.function-call.arguments.python
    - none
    - token.variable.parameter.java
    - token.package
    - support.type.property-name
    - support.constant.property-value
    - meta.tag
    - markup.heading.setext
    - punctuation.section.array.begin.php
    - punctuation.section.array.end.php
    - punctuation.definition.parameters.begin.bracket.round.php
    - punctuation.definition.parameters.end.bracket.round.php
    - punctuation.separator.delimiter.php
    - punctuation.section.scope.begin.php
    - punctuation.section.scope.end.php
    - punctuation.terminator.expression.php
    - punctuation.definition.arguments.begin.bracket.round.php
    - punctuation.definition.arguments.end.bracket.round.php
    - punctuation.definition.storage-type.begin.bracket.round.php
    - punctuation.definition.storage-type.end.bracket.round.php
    - punctuation.definition.array.begin.bracket.round.php
    - punctuation.definition.array.end.bracket.round.php
    - punctuation.definition.begin.bracket.round.php
    - punctuation.definition.end.bracket.round.php
    - punctuation.definition.begin.bracket.curly.php
    - punctuation.definition.end.bracket.curly.php
    - punctuation.definition.section.switch-block.end.bracket.curly.php
    - punctuation.definition.section.switch-block.start.bracket.curly.php
    - punctuation.definition.section.switch-block.begin.bracket.curly.php
    - punctuation.definition.section.switch-block.end.bracket.curly.php
    - function.parameter
    - function.brace
    - function.parameter.ruby
    - function.parameter.cs
    - block.scope.end
    - block.scope.begin
    - meta.template.expression
  lightDark:
    - comment
    - punctuation.definition.comment
  chalky:
    - markup.changed.diff
    - support.constant.math
    - storage.type.annotation.java
    - storage.modifier.import.java
    - storage.type.java
    - support.module.node
    - support.type.object.module
    - support.module.node
    - entity.name.type.module
    - import.storage.java
    - entity.name.type.namespace
    - support.class
    - entity.name.type.class
    - entity.name.class.identifier.namespace.type
    - entity.name.class
    - variable.other.class.js
    - variable.other.class.ts
    - entity.name.type
    - token.storage.type.java
    - punctuation.definition.bold
    - support.other.namespace.use.php
    - support.other.namespace.use-as.php
    - support.other.namespace.php
    - entity.other.alias.php
    - meta.interface.php
    - storage.type.php
    - meta.other.type.phpdoc.php
    - keyword.other.type.php
    - keyword.other.array.phpdoc.php
    - var.this
    - variable.language.this.js
    - variable.language.this.ts
    - variable.language.this.jsx
    - variable.language.this.tsx
    - support.type.primitive.ts
    - support.type.builtin.ts
    - support.type.primitive.tsx
    - support.type.builtin.tsx
    - storage.type.cs
    - support.type.primitive
    - keyword.operator.assignment.go
    - keyword.operator.address.go
    - entity.name.package.go
    - entity.global.clojure
    - source.makefile
    - storage.modifier.import.groovy
    - support.variable.semantic.hlsl
    - support.type.swift
    - support.type.vb.asp
    - variable.language.self
    - variable.language.this
  malibu:
    - meta.diff.header.from-file
    - punctuation.definition.from-file.diff
    - keyword.operator.expression.import
    - meta.method.java
    - entity.name.function
    - support.function.console
    - meta.function-call.generic.python
    - entity.name.function
    - meta.require
    - support.function.any-method
    - variable.function
    - keyword.other.special-method
    - entity.other.attribute-name.id
    - markup.headingpunctuation.definition.heading
    - entity.name.section
    - string.other.link.title.markdown
    - string.other.link.description.markdown
    - meta.function-call.php
    - meta.function-call.object.php
    - meta.function-call.static.php
    - entity.name.goto-label.php
    - support.other.php
    - meta.function.decorator.python
    - token.info-token
    - support.type.type.flowtype
    - meta.method.groovy
  fountainBlue:
    - keyword.operator.logical.js
    - keyword.operator.bitwise
    - keyword.operator.channel
    - keyword.operator.css
    - keyword.operator.scss
    - keyword.operator.less
    - support.type.vendored.property-name.css
    - keyword.operator
    - support.type.object.dom
    - keyword.operator.arithmetic
    - keyword.operator.comparison
    - keyword.operator.decrement
    - keyword.operator.increment
    - support.type.posix-reserved.c
    - support.type.python
    - support.function
    - constant.other.symbol
    - string.regexp
    - constant.character.escape
    - source.jsonmeta.structure.dictionary.json>constant.language.json
    - source.jsonmeta.structure.array.json>constant.language.json
    - keyword.operator.logical.php
    - keyword.operator.bitwise.php
    - keyword.operator.arithmetic.php
    - keyword.operator.comparison.php
    - support.token.decorator.python
    - meta.function.decorator.identifier.python
    - constant.language.symbol.ruby
    - rgb-value
    - keyword.operator.assignment
    - support.type.prelude.elm
    - entity.other.attribute-name.pseudo-element
    - entity.other.attribute-name.pseudo-class
    - constant.keyword.clojure
    - keyword.operator
    - punctuation.separator
    - punctuation.terminator
  invalid:
    - invalid.illegal
    - invalid.broken
    - invalid.deprecated
    - invalid.unimplemented
fontStyle:
  italic:
    - comment
    - punctuation.definition.comment
    - entity.other.attribute-name.js
    - entity.other.attribute-name.ts
    - entity.other.attribute-name.jsx
    - entity.other.attribute-name.tsx
    - variable.parameter
    - variable.language.super
    - comment.line.double-slash
    - comment.block.documentation
    - keyword.control.import.python
    - keyword.control.flow.python
    - markup.quote.markdown
    - markup.italic.markdown
    - var.this
    - variable.language.this.js
    - variable.language.this.ts
    - variable.language.this.jsx
    - variable.language.this.tsx
    - keyword.control
    - storage
    - variable.language.self
    - variable.language.this
  normal:
    - entity.other.attribute-name.id
    - entity.other.attribute-name.class.css
    - storage.type.function.arrow
  bold:
    - markup.heading
    - markup.bold
    - todo.bold
    - markup.bold.markdown
